GRANT CREATE MINING MODEL TO "C##ROB";
GRANT SELECT ANY MINING MODEL TO "C##ROB";
GRANT ALTER ANY MINING MODEL TO "C##ROB";
GRANT DROP ANY MINING MODEL TO "C##ROB";
GRANT COMMENT ANY MINING MODEL TO "C##ROB";