---
title: "Week 5 Difference - Parametric Tests"
output:
  html_document:
    df_print: paged
editor_options:
  chunk_output_type: console
---


 
### SETUP
```{r}

#We are using a .dat file (survey.dat) created from the SPSS file survey.sav  taken from SPSS Survival Manual 6th Edition Julie Pallant
#http://spss.allenandunwin.com.s3-website-ap-southeast-2.amazonaws.com/data-files.html#.Wb0vvnWP-po
#Results on a survey on well being
#We need to load the file so that we can use it in R.
survey <- read.table("survey.dat")
#Setting the column names to be that used in the dataset
colnames(survey) <- tolower(colnames(survey))

needed_packages <- c("pastecs", "ggplot2", "psych", "semTools", "FSA", "car", "coin", "rstatix")                      
# Extract not installed packages
not_installed <- needed_packages[!(needed_packages %in% installed.packages()[ , "Package"])]    
# Install not installed packages
if(length(not_installed)) install.packages(not_installed) 

library(pastecs) #For creating descriptive statistic summaries
library(ggplot2) #For creating histograms with more detail than plot
library(psych) # Some useful descriptive functions
library(semTools) #For skewness and kurtosis
library(FSA) #For percentage
library(car) # For Levene's test for homogeneity of variance 
library(effectsize) #To calculate effect size for t-test
```

### tslfest Generate histogram
```{r}

#We will allocate the histogram to a variable to allow use to manipulate it
gg <- ggplot(survey, aes(x=tslfest))

#Change the label of the x axis
gg <- gg + labs(x="Total Self-esteem")

#manage binwidth and colours
gg <- gg + geom_histogram(binwidth=2, colour="black", aes(y=..density.., fill=..count..))
gg <- gg + scale_fill_gradient("Count", low="#DCDCDC", high="#7C7C7C")

#adding a normal curve
#use stat_function to compute a normalised score for each value of tslfest
#pass the mean and standard deviation
#use the na.rm parameter to say how missing values are handled
gg <- gg + stat_function(fun=dnorm, color="red",args=list(mean=mean(survey$tslfest, na.rm=TRUE), sd=sd(survey$tslfest, na.rm=TRUE)))

#to display the graph request the contents of the variable be shown
gg
```
### tslfest Generate Q-Q Plot
```{r}
#Create a qqplot
qqnorm(survey$tslfest)
qqline(survey$tslfest, col=2) #show a line on theplot
```


### tslfest Generate Summary Statistics 
```{r}

#stat.desc is a function from pastecs - make sure you include the basic switch=F to ensure you don't get scienfitic notation
pastecs::stat.desc(survey$tslfest, basic=F)

#We can make our decision based on the value of the standardised score for skew and kurtosis
#We divide the skew statistic by the standard error to get the standardised score
#This will indicate if we have a problem
tpskew<-semTools::skew(survey$tslfest)
tpkurt<-semTools::kurtosis(survey$tslfest)
tpskew[1]/tpskew[2]

tpkurt[1]/tpkurt[2]

#and by calculating the percentage of standardised scores for the variable itself that are outside our acceptable range
#This will tell us how big a problem we have
# Calculate the percentage of standardised scores that are greated than 1.96
# the perc function which is part of the FSA package which calculate the percentage that are within a range - you can look for greater than "gt", greater than or equal "geq", "gt", less than or equal "leq",  or less than "lt"),
# scale is a function that creates z scores, abs gets absolute value

ztslfest<- abs(scale(survey$tslfest))

FSA::perc(as.numeric(ztslfest), 1.96, "gt")
FSA::perc(as.numeric(ztslfest), 3.29, "gt")

```

### Differences - Parametric Tests
#### Independent t-test
##### Describe Self-estemm by group (smoker v non-smoker - variable smoke)
```{r Describe}
#Get descriptive stastitics by group - output as a matrix
psych::describeBy(survey$tslfest, survey$smoke, mat=TRUE)

#Conduct Levene's test for homogeneity of variance in library car - the null hypothesis is that variances in groups are equal so to assume homogeneity we woudl expect probaility to not be statistically significant.
car::leveneTest(tslfest ~ smoke, data=survey)
#Pr(>F) is your probability - in this case it is not statistically significant so we can assume homogeneity


#Conduct the t-test from package stats
#In this case we can use the var.equal = TRUE option to specify equal variances and a pooled variance estimate
stats::t.test(tslfest~smoke,var.equal=TRUE,data=survey)
#No statistically significant difference was found

res <- stats::t.test(tslfest~smoke,var.equal=TRUE,data=survey)
#Calculate Cohen's d
#artithmetically
effcd=round((2*res$statistic)/sqrt(res$parameter),2)

#Using function from effectsize package
effectsize::t_to_d(t = res$statistic, res$parameter)


#Eta squared calculation
effes=round((res$statistic*res$statistic)/((res$statistic*res$statistic)+(res$parameter)),3)
effes


```
### Reporting the results with Cohen's d effect

```
An independent-samples t-test was conducted to compare self-esteem scores for respondents who smoke and those who do not smoke. No significant difference in the scores for self-esteem was found (M=33.20, SD= 5.79 for respondents who smoke, M= 33.64, SD= 5.30 for respondents who do not smoke), (t(`r res$parameter`)= `r round(res$statistic,3)`, p = `r round(res$p.value,2)`. Cohen's d also indicated a very small effect size (`r effcd`).

```

### Reporting the results with eta squred effect

```
An independent-samples t-test was conducted to compare self-esteem scores for respondents who smoke and those who do not smoke. No significant difference in the scores for self-esteem was found (M=33.20, SD= 5.79 for respondents who smoke, M= 33.64, SD= 5.30 for respondents who do not smoke), (t(`r res$parameter`)= `r round(res$statistic,3)`, p = `r round(res$p.value,2)`. A very small effect size was also indicted by the eta squared value (`r effes`).

```


