---
title: "2. Data Collection & Preparation"
output:
  html_document:
    df_print: paged
---

According to (Cortez, et al), the student performance dataset was collected to develop a method of predicting student achievement and identify the key variables that affect their educational success or failure. In this section we studied and discussed how this was carried out. We noted any sampling concerns (validity, reliability etc.), as they became apparent. We also discuss preparation steps, within the constraints of available information.

## How Data was collected
The dataset was collected from two Portuguese secondary schools by two different methods; using existing reports containing student marks and conducting a 37 question, single page questionnaires, completed by 788 students. The questionnaire was meant to complement the student marking report which contained limited information such as grades and the number of absences that were available. The questionnaire gave viability on socioeconomic and school related attributes.

After reviewing "Using Data Mining to Predict Secondary School Student Performance” by (Cortez, et al, 2018), the following attributes listed below were studied.

### Attribute Types

#### School Attribute
* **school**: Mousinho da Silveira (**MS**) & Gabriel Pereira (**GP**), <span style="color:blue">dichotomous (binary)</span>

#### Student Attributes
* **sex**: [**F**emale / **M**ale], <span style="color:blue">dichotomous (binary)</span>,
* **age**: Age of the student [**years old**], numeric
* **address**: Living in [**R**ural] area or [**U**rban], <span style="color:purple">categorical (nominal)</span>, should be dichotomous (binary)
* **Pstatus**: if parents are [**T**ogether] or [**A**part], <span style="color:purple">categorical (nominal)</span>, should be dichotomous (binary)
* **Medu**: mother's education level [**0-4**], <span style="color:green">categorical (ordinal)</span>,
* **Mjob**: mother's job [**teacher, health care related, civil service, home, other**], <span style="color:purple">categorical (nominal)</span>, 
* **Fedu**: father's education level [**0-4**], <span style="color:green">categorical (ordinal)</span>,
* **Fjob**: father's job [**teacher, health care related, civil service, home, other**], <span style="color:purple">categorical (nominal)</span>,
* **reason**: reason for choosing the school [**close to home, school reputation, course preference or other**],
* **nursery**: attended a nursery school [**Y/N**], <span style="color:blue">dichotomous (binary)</span>,
* **internet**: internet access is at home [**Y/N**], <span style="color:blue">dichotomous (binary)</span>,

#### Maths & Language Attributes
* **guardian**: mother, father or other are the student's guardian, <span style="color:green">categorical (ordinal)</span>,
* **traveltime**: home to school travel time [**1-4**], <span style="color:red">numeric</span>, (based on categorical (ordinal) as numeric),
* **studytime**: amount of time per week spent studying [**1-4**], <span style="color:red">numeric</span>, (based on categorical (ordinal) as numeric)
* **failures**: past number of class failures [**1-4**], <span style="color:red">numeric</span>,(based on categorical (ordinal) as numeric),
* **schoolsup**: school provides extra educational support [**Y/N**], <span style="color:blue">dichotomous (binary)</span>,
* **famsup**: family provides extra educational support [**Y/N**], <span style="color:blue">dichotomous (binary)</span>,
* **paidclass**: student gets grinds [**Y/N**], <span style="color:blue">dichotomous (binary)</span>,
* **activities**: student takes extra-curricular activities [**Y/N**], <span style="color:blue">dichotomous (binary)</span>,
* **higher**: wants to go onto higher education [**Y/N**], <span style="color:blue">dichotomous (binary)</span>,
* **famsize**: family size [**≤3** or **>3**], <span style="color:red">numeric</span>,(based on categorical (ordinal) as scale numeric),
* **romantic**: with a romantic relationship [**Y/N**], <span style="color:blue">dichotomous (binary)</span>,
* **famrel**: quality of family relationships [**1-5**], <span style="color:red">numeric</span>,(based on categorical (ordinal) as numeric),
* **freetime**: free time after school [**1-5**], <span style="color:red">numeric</span>,(based on categorical (ordinal) as numeric),
* **goout**: going out with friends [**1-5**], <span style="color:red">numeric</span>,(based on categorical (ordinal) as ratio numeric),
* **Dalc**: workday alcohol consumption [**1-5**], <span style="color:red">numeric</span>,(based on categorical (ordinal) as ratio numeric),
* **Walc**: weekend alcohol consumption [**1-5**], <span style="color:red">numeric</span>,(based on categorical (ordinal) as ratio numeric),
* **health**: current health of students [**1-5**], <span style="color:red">numeric</span>,(based on categorical (ordinal) as numeric),
* **absences**: school absences [**0-93**], <span style="color:red">numeric</span>,(based on categorical (ordinal) as numeric),
* **G1**: first period score for maths and Portuguese language [**0-20**], <span style="color:red">numeric</span>,(based on categorical (ordinal) as numeric),
* **G2**: second period score for maths and Portuguese language [**0-20**],<span style="color:red">numeric</span>,(based on categorical (ordinal) as numeric),
* **G3**: final period score for maths and Portuguese language [**0-20**], <span style="color:red">numeric</span>,(based on categorical (ordinal) as numeric),

## Sampling Concerns and Preparation Steps
A main concern with this data relates to validity. In the following we list some of those concerns. This report used statistical methods to try and answer what levels indicate in our data that a student will fail their exams. Validity according to (Nantais, 2019) is a measure of whether this data will support our conclusions or not, we need to ensure that our independent variables actually *cause* a change to our dependent variables. There are four types of validity we needd to consider; statistical conclusion, construct, external and internal validity. 

For preparations we needed to ensure that the data used for our linear regression analysis had linearity, homoscedasticity, multivariate normality, was independent of errors and lacked multicolliniarity. Integration of data from multiple sources has already been done for us. We assumed that duplicate entries were removed and units were converted. We assumed that there may be null or empty values in the dataset and will be cautious during data processing. Categorical variables such as Sex and parents' jobs will needed to be encoded but we needed to ensure they were separated into new dummy variable columns to avoid multicollinearity. As in where our linear regression model can't tell the different between the two encoded variables and causes issues with our predictability. R does this dummy variable generation for us.

### Nominal & Ordinal Categorical Variables
#### Sampling Concern
* 'Mjob' and 'Fjob' relate to the profession of the student's parents. According to (Cortez et al, 2018) they are "teacher, health care related, civil services (e.g. administrative or police), at home or other". These professions types seem very narrow and don't include Arts and entertainment, Business administration or Industrial and manufacturing which may cause issues with External validity, if we wanted to scale up to other schools. It also causes Construct validity because parents income is the higher order attribute they are trying to obtain which why were unable to do so in their survey as many students left it blank.
* 'guardian' relates to the student's guardian. The only values it holds are mother, father and other. There is no explanation if this indicates whether the parents are still together, separated or if one has passed away. (Hovens et al. 2009) investigated the association between childhood life events, childhood trauma and the presence of anxiety, depressive disorders in adulthood. They included the adverse life event of divorce of parents, early parental loss and ‘placed in care’. It is unfortunate that in (Cortez, et al, 2018) paper, this was not considered. (Tiet et All, 1998) found children at risk of higher levels of adverse life events were more resilient if they had a better family function, more adults in the household and closer parental monitoring. This would suggest an interesting dependent variable to compare with student grades. 
* 'reason' relates to the reason to choose this school. Options are "close to home, school reputation, course preference or other". This seems vague to whether it is asking why the parents chose the school, why the student likes the school or why the student would recommend the school to others. This may pose an issue with Internal validity as our dependent variable may change regardless of this independent variable. One of (Cortez, et al, 2018) research question relates to "What are the main reasons for student transfers" and in their conclusion seem to suggest 'reason to choose school' affects student performance but state that more research is required to understand. This seems to suggest 'reason' relates to why a student transferred to the school.
* higher is relation to students motivation to go on and persue a higher education. This appears to be focused on university studies, no information is given on apprenticeships or vocational training. Poor performing students may excel in these areas.
* first grade and second grade scores are given without any information around them begging the question as to what factors cause their increase. We are not given a time attribute on which to determine this.
* health does not indicate if the student has a learning impairment which would otherwise impact their grades. dyslexia, dyscalculia, hearing or vision impairment would all be examples of health related concerns.

#### Preparation steps
* Nominal variables like 'Mjob', 'Fjob', 'guardian' and 'reason' are categorical that have no order to them.
* Medu, Fedu and health are examples of ordinal categorical variables, they have some order to them (e.g low, medium and high)
* Categorical variables will be displayed in either a pie chart, bar chart or stacked bar chart where applicable.

### Binary (Dichotomous) Variables
#### Sampling Concern
* activities.m does not indicate if the activity relates to maths or not and gives reliability concerns whether this will be useful to our dependent variable (final grades).
* internet seems to be in most homes and so there is internal validity concerns whether this will be important to whether a student will get bad grades or not.

#### Preparation steps
* These variables can only take one of two values, 0 or 1. Several variables such as internet take this data type. Similar to Categorical variables we can visualise these with bar and pie charts.
* For 'activities' attribute it is not clear if this relates to the subject or not, as in if the student is attending activities that relate to Maths or Portuguese.
* Most of our data is categorical or numerical, we will need to convert 'yes/no' responses into binary such as schoolsup.m


### Numerical Variable
#### Sampling Concern
* absences
* first, second and third period
#### Preparation steps
* Variables like age have values that describe some measurable quantity. Numeric variables can be discrete or continuous. 
* Age is an example of a continuous numeric variable because it can be a fraction where as discrete variables cannot, e.g number of students in a class. These type of variables can also be broken into interval or ratio scale. Ratio scale have a true zero (e.g bank balance equals zero euro). We will use scatter plots, QQ-plots and histograms to graph this type of data.
* Our data will need to be absence of outliers, normally distributed and homoskedasticity (i.e little to no skewness). We have >80 observation so will treat z-score outside +/-3.27, such as math student absences as outliers. Using age as an example again, we will replace with highest age value with the max quartile +1.
#### Preparation steps
We will ensure numerical data is normally distributed where possible and will handle outliers where found.
