#use readr library and read in csv file
library(readr)

#students <- read_delim('./dataset.csv', delim=';', na=c('unknown'), col_types = 'nccccncccncnnnncc')
student = read.table("dataset.csv", sep = ",", header=TRUE)



#basic checks
problems(student)
nrow(student) #382 observations / rows / datapoints
ncol(student) # 53 attributes or features

# we take a look at our columns and their type in our dataset
str(student) 

#feature vector below
#nominal attributes
  # $ school      : chr  "GP" "GP" "GP" "GP" ...

#binary attributes (symmetric)
# $ sex         : chr  "F" "F" "F" "F" ...
# $ address     : chr  "R" "R" "R" "R" ...
# $ famsize     : chr  "GT3" "GT3" "GT3" "GT3" ...
# $ nursery     : chr  "yes" "no" "yes" "yes" ...
# $ internet    : chr  "yes" "yes" "no" "yes" ...
# $ guardian.m  : chr  "mother" "mother" "mother" "mother" ...
# $ schoolsup.m : chr  "yes" "yes" "yes" "yes" ...
# $ famsup.m    : chr  "yes" "yes" "yes" "yes" ...
# $ paid.m      : chr  "yes" "no" "yes" "yes" ...
# $ activities.m: chr  "yes" "no" "yes" "yes" ...
# $ higher.m    : chr  "yes" "yes" "yes" "yes" ...
# $ romantic.m  : chr  "no" "yes" "no" "no" ...
# $ guardian.p  : chr  "mother" "mother" "mother" "mother" ...

#numeric attributes (interval-scaled attributes, discrete attribute)
# $ age         : int  15 15 15 15 15 15 15 15 15 15 ...


# $ Pstatus     : chr  "T" "T" "T" "T" ...
# $ Medu        : int  1 1 2 2 3 3 3 2 3 3 ...
# $ Fedu        : int  1 1 2 4 3 4 4 2 1 3 ...
# $ Mjob        : chr  "at_home" "other" "at_home" "services" ...
# $ Fjob        : chr  "other" "other" "other" "health" ...
# $ reason      : chr  "home" "reputation" "reputation" "course" ...
# $ traveltime.m: int  2 1 1 1 2 1 2 2 2 1 ...
# $ studytime.m : int  4 2 1 3 3 3 3 2 4 4 ...
# $ failures.m  : int  1 2 0 0 2 0 2 0 0 0 ...
# $ famrel.m    : int  3 3 4 4 4 4 4 4 4 4 ...
# $ freetime.m  : int  1 3 3 3 2 3 2 1 4 3 ...
# $ goout.m     : int  2 4 1 2 1 2 2 3 2 3 ...
# $ Dalc.m      : int  1 2 1 1 2 1 2 1 2 1 ...
# $ Walc.m      : int  1 4 1 1 3 1 2 3 3 1 ...
# $ health.m    : int  1 5 2 5 3 5 5 4 3 4 ...
# $ absences.m  : int  2 2 8 2 8 2 0 2 12 10 ...
# $ traveltime.p: int  2 1 1 1 2 1 2 2 2 1 ...
# $ studytime.p : int  4 2 1 3 3 3 3 2 4 4 ...
# $ failures.p  : int  0 0 0 0 0 0 0 0 0 0 ...
# $ schoolsup.p : chr  "yes" "yes" "yes" "yes" ...
# $ famsup.p    : chr  "yes" "yes" "yes" "yes" ...
# $ paid.p      : chr  "yes" "no" "no" "no" ...
# $ activities.p: chr  "yes" "no" "yes" "yes" ...
# $ higher.p    : chr  "yes" "yes" "yes" "yes" ...
# $ romantic.p  : chr  "no" "yes" "no" "no" ...
# $ famrel.p    : int  3 3 4 4 4 4 4 4 4 4 ...
# $ freetime.p  : int  1 3 3 3 2 3 2 1 4 3 ...
# $ goout.p     : int  2 4 1 2 1 2 2 3 2 3 ...
# $ Dalc.p      : int  1 2 1 1 2 1 2 1 2 1 ...
# $ Walc.p      : int  1 4 1 1 3 1 2 3 3 1 ...
# $ health.p    : int  1 5 2 5 3 5 5 4 3 4 ...
# $ absences.p  : int  4 2 8 2 2 2 0 0 6 10 ...

#numeric attributes (ratio-scalled)
# $ mG1         : int  7 8 14 10 10 12 12 8 16 10 ...
# $ mG2         : int  10 6 13 9 10 12 0 9 16 11 ...
# $ mG3         : int  10 5 13 8 10 11 0 8 16 11 ...

# $ pG1         : int  13 13 14 10 13 11 10 11 15 10 ...
# $ pG2         : int  13 11 13 11 13 12 11 10 15 10 ...
# $ pG3         : int  13 11 12 10 13 12 12 11 15 10 ...

#we check for any N/A or any issues with values by viewing top and bottom of dataset
head(student)
tail(student)
#check for na
for (i in ncol(student)){
  ifelse(is.na(student[[i]]),print(student[[i]]),print("all good"))
}# no na's found

#now we convert characters to factors
#with loops
factor_indices <- c(1:30, 34:50)
for (i in factor_indices){
  student[[i]] <- as.factor(student[[i]])
}

numeric_indices <- c(31:33, 51:53)
for (i in numeric_indices){
  student[[i]] <- as.numeric(student[[i]])
}
#descriptive statistics
summary(student)

columns <- c(names(student))
for (i in columns){
  name = str_replace(i, ".", "-")
  png(file = paste("plots/", name, ".png"))
  plot(student[i],xlab=i)
  dev.off()
}

mG1 = hist(student$mG1,main = paste("Histogram of" , "mG1"), xlab="mG1", ylab="score", col="lightblue")
text(mG1$mids,mG1$counts,labels=mG1$counts, adj=c(0.5, -0.5))

hist(student$mG2,main = paste("Histogram of" , "mG2"), xlab="mG2", ylab="score", col="lightblue")
hist(student$mG3,main = paste("Histogram of" , "mG3"), xlab="mG3", ylab="score", col="lightblue")
hist(student$pG1,main = paste("Histogram of" , "pG1"), xlab="pG1", ylab="score", col="lightgreen")
hist(student$pG2,main = paste("Histogram of" , "pG2"), xlab="pG2", ylab="score", col="lightgreen")
hist(student$pG3,main = paste("Histogram of" , "pG3"), xlab="pG3", ylab="score", col="lightgreen")

