-- SECTION A: Data Warehouse Modelling
-- Generated by Oracle SQL Developer Data Modeler 21.4.1.349.1605
--   at:        2021-12-31 16:26:56 GMT
--   site:      Oracle Database 21c
--   type:      Oracle Database 21c



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE call_dim (
    cd_id          NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1),
    call_time      DATE,
    phone_number   VARCHAR2(32),
    call_type_name VARCHAR2(32),
    call_duration  FLOAT
);

ALTER TABLE call_dim ADD CONSTRAINT call_dim_pk PRIMARY KEY ( cd_id );

CREATE TABLE cus_dim (
    cusd_id           NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1),
    phone_number      VARCHAR2(26),
    date_of_birth     DATE,
    social_grade_name VARCHAR2(26),
    plan_name         VARCHAR2(26),
    plan_start_date   DATE,
    plan_end_date     DATE
);

ALTER TABLE cus_dim ADD CONSTRAINT cus_dim_pk PRIMARY KEY ( cusd_id );

CREATE TABLE dates_dim (
    dd_id                NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1),
    date_time             DATE,
    full_date_description VARCHAR2(32),
    day_of_week           NUMBER,
    month                 NUMBER,
    year                  NUMBER,
    week_num              NUMBER,
    quarter               NUMBER
);

ALTER TABLE dates_dim ADD CONSTRAINT dates_dim_pk PRIMARY KEY ( dd_id );

CREATE TABLE rates_dim (
    rd_id        NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1),
    plan_name    VARCHAR2(26),
    call_type    VARCHAR2(26),
    cost_per_min FLOAT NOT NULL
);

ALTER TABLE rates_dim ADD CONSTRAINT rates_dim_pk PRIMARY KEY ( rd_id );

CREATE TABLE call_facts (
    cf_id                  NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1),
    dates_dim_dd_id        NUMBER NOT NULL,
    cus_dim_cusd_id        NUMBER(38) NOT NULL,
    call_dim_cd_id         NUMBER NOT NULL,
    rates_dim_rd_id        NUMBER NOT NULL,
    customer_age           NUMBER,
    customer_social_grade  VARCHAR2(32),
    customer_contract_plan VARCHAR2(32),
    days_on_plan      NUMBER,
    call_revenue_generated FLOAT,
    cus_service_time       FLOAT,
    customer_active        NUMBER
);

ALTER TABLE call_facts ADD CONSTRAINT call_facts_pk PRIMARY KEY ( cf_id );

ALTER TABLE call_facts
    ADD CONSTRAINT call_facts_call_dim_fk FOREIGN KEY ( call_dim_cd_id )
        REFERENCES call_dim ( cd_id );

ALTER TABLE call_facts
    ADD CONSTRAINT call_facts_cus_dim_fk FOREIGN KEY ( cus_dim_cusd_id )
        REFERENCES cus_dim ( cusd_id );

ALTER TABLE call_facts
    ADD CONSTRAINT call_facts_dates_dim_fk FOREIGN KEY ( dates_dim_dd_id )
        REFERENCES dates_dim ( dd_id );

ALTER TABLE call_facts
    ADD CONSTRAINT call_facts_rates_dim_fk FOREIGN KEY ( rates_dim_rd_id )
        REFERENCES rates_dim ( rd_id );